### ISSUE TITLE
Bot-Detector shows as installed but not-functional or changeable (within the past 26hrs)

### ISSUE THREAD

**Issue by ltmetalman** [Bot-detector/bot-detector#125]
Since logging off 6-13 9pm CDT, my Runelite seems to have booted, But my sidebar looks a lot smaller. (So this may have affected other apps in addition Bot-detector) I lost the ability to 'predict' players, as well. Below, I combined 2 screenshots for easier viewing. On the left picture I am hovering over a lvl 14 in motherload mine by the chest. Can't predict them, nor the person under them. On the right is my sidebar, empty of Bot-detector. But you can see it IS installed in the 'plugin hub' just with no setting-cog next to it. Just the option to remove.

Uninstall and reinstall gets it back, but I'm just wondering why it was kicked out in the first place, and if this affected other plugins. I see two updates happened in the time period from the title. Wondering if that has anything to do with it too..

I am on Windows 10, which has pushed some really dumb (opinion) updates without asking users for permission, including deleting ms word and excel, and adding an msn bar. If there is any information that relates this to Win10, please let me know so I can get enraged enough to switch to Linux once and for all.. or at least side-boot...

![botdetector6-14-21_11-09-CDT](https://user-images.githubusercontent.com/54198179/121991896-28374080-cd66-11eb-800e-4b7b6b2ccc53.jpg)

**Comment by Cyborger1** [comment]
Is this issue affecting only this plugin, or all plugin hub plugins? If it's the latter, you should probably go on the Runelite discord in the support channel.

**Comment by extreme4all** [comment]
Are you logged in, into runelite? if not you might just be on the default settings or your settings might have been reset.

**Comment by ltmetalman** [comment]
It only affected bot detector, it was in runelite so I was logged into runelite. I make this more as something to make you aware of an issue. As I said, it was fixed by uninstalling and reinstalling bot detector.

**Comment by Cyborger1** [comment]
Could you provide a `client.log` from around when the issue happened then? If our plugin is at fault then I'd like to inspect your logs to see if there's anything out of place.

**Comment by ltmetalman** [comment]
Ah, I always wondered where those were.
I see that on 6-14 when I logged on there were a lot of errors, and there's a separate log that just documents errors...

Sorry if this is too many files, I am rarely able to be near my home computer, because I work 2nd shift with OT. so i can't really respond with anything useful till 1am my time....
I included logs from 6-13, 6-14, and a curious one where 4 logs were created that were basically identical, other than the timestamp.

Just 10mb of
[[[timestamp]]] [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null

I'm always interested in what this means, I just can't respond often, so apologies again for that.

[client_2021-06-14.1.log](https://github.com/Bot-detector/bot-detector/files/6674993/client_2021-06-14.1.log)
[launcher_2021-06-14.0.log](https://github.com/Bot-detector/bot-detector/files/6674987/launcher_2021-06-14.0.log)
[client_2021-06-13.0.log](https://github.com/Bot-detector/bot-detector/files/6674988/client_2021-06-13.0.log)
[launcher_2021-06-13.0.log](https://github.com/Bot-detector/bot-detector/files/6674989/launcher_2021-06-13.0.log)
[client_2021-06-15.3.log](https://github.com/Bot-detector/bot-detector/files/6674991/client_2021-06-15.3.log)
[client_2021-06-15.0.log](https://github.com/Bot-detector/bot-detector/files/6674992/client_2021-06-15.0.log)
[client_2021-06-14.0.log](https://github.com/Bot-detector/bot-detector/files/6674985/client_2021-06-14.0.log)

**Comment by Cyborger1** [comment]
The error seems to be in the last file `client_2021-06-14.0.log`.
```
2021-06-14 23:02:23 [RuneLite] ERROR n.r.c.e.ExternalPluginManager - Unable to download external plugins
java.net.UnknownHostException: No such host is known (repo.runelite.net)
```
It seems like your internet had some DNS issues and couldn't connect to download the plugins.

All the `n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering java.lang.NullPointerException: null` come from the Max Hit plugin hub plugin:
```
2021-06-14 23:34:22 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
	at com.maxhit.MaxHitPlugin.strengthBonus(MaxHitPlugin.java:715)
	at com.maxhit.MaxHitPlugin.maxHitBase(MaxHitPlugin.java:742)
	at com.maxhit.MaxHitOverlay.render(MaxHitOverlay.java:43)
```
It seems like the issue stems from equipping an item with no defined stats. There should probably be a null check [on that line](https://github.com/Matt12yearslater/max-hit/blob/5d5e94ae6a364ab8ae44333626386584d0baef2d/src/main/java/com/maxhit/MaxHitPlugin.java#L715). I recommend you raise this issue on his repo.

I'll be closing this as it was not an issue on our end.
