### ISSUE TITLE
Auto-upload only captures a small portion of players in Blast Furnace

### ISSUE THREAD

**Issue by Mason0567** [Bot-detector/bot-detector#142]
While in the Blast Furnace room, only 5-15 players are automatically uploaded each cycle despite ~50 players being present. This issue consistently occurs while remaining in the room for the entire period between uploads.

Bot Detector Version 1.3.5
Runelite Version 1.7.19
OSRS Rev 198
Launcher version 2.1.6

![image](https://user-images.githubusercontent.com/39751299/128536419-7f28b0f5-4bd1-4988-8a2b-4c5a19db0ba0.png)

**Comment by Cyborger1** [comment]
This is intended behaviour, players are only logged whenever they trigger a spawn event, such as when entering the room. If a player doesn't leave and come back in the room between two uploads, they will not be logged.
