### ISSUE TITLE
Twitter panel in the plugin

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/bot-detector#150]
I'd like to see the official tweets via the plugin sidebar menu. This may be beneficial as we'd be able to expand our followership on twitter, as well as display statistics and other information to plugin users  that they might not know of otherwise!

I'm thinking that it could be similar to the newsfeed output, and maybe placed underneath the prediction box?

![image](https://user-images.githubusercontent.com/5789682/143235471-af389e31-948c-4139-b4cb-86ffa5fd3760.png)
![image](https://user-images.githubusercontent.com/5789682/143235585-9a40362c-cfff-42c6-83ce-9ae6e0877117.png)

Let me know what you think :D

**Comment by Cyborger1** [comment]
I don't think it's relevant for the plugin to display a twitter feed like this, there's not really space for it without making another panel and there's already a twitter button on the panel anyway.

I also don't think the plugin can plug to twitter's API directly either, I looked at how Runelite does theirs and it involves some pre-made Feed file pulled from their own API. They probably handle all twitter stuff on that end.

This would be a lot of work and I don't really see the advantage. Sorry.

**Comment by Ferrariic** [comment]
Thanks, you bring up a lot of good points. I'll close the issue - tyvm!
