### ISSUE TITLE
Remove Breakdown Prediction for Stats too Low 

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/bot-detector#159]
We'd like to do the following:

In cases of Stats too low (ex. an account below 2m xp) we would remove the breakdown predictions, as they're not entirely relevant.
Let us know if you think this would be a good change ✅ , or to keep the current system ❌.
>✅ 55
>❌ 5

This can be a default off config for stats too low, and allow users to toggle it on -- if they'd like to.

**Comment by Cyborger1** [comment]
I feel this should be on the API side no? The API should not return a prediction breakdown for these people.

**Comment by Ferrariic** [comment]
There's a discussion to have it still send it on the API side, but have a yes/no toggle on the plugin side, so we're looking at that atm.

**Comment by Cyborger1** [comment]
We'd either need to have an extra field in the data sent to the plugin (I'm not a fan of having to look for a hard coded string 'stats too low') or have a parameter on the route to send the breakdown or not when that condition happens.

**Comment by Ferrariic** [comment]
Should be solved on API side
