### ISSUE TITLE
Current reports higher than total

### ISSUE THREAD

**Issue by gnorfix** [Bot-detector/bot-detector#171]
So i've been doing pest controll for about 10 hours and the current uploads are getting higher than total ones. Might this be by tagging the same people each game?

https://prnt.sc/ocYtarSNu_xh

**Comment by Cyborger1** [comment]
Hey, this is "somewhat" intended. The way the plugin works is that current uploads is just a count of username/region pairs that were sent to the server, while Total is a tally of unique names of other players you've seen at least once.

It's entirely possible for current uploads to get bloated on longer play sessions, as it is true the same players may be counted multiple times.

It would be possible to "fix" by keeping track of already sent name/region pairs, but that would introduce unnecessary memory usage that we opted to avoid.

I hope this answers your questions, you may close the issue if you're good with this.
