### ISSUE TITLE
[Social Media] - Social Media presence

### ISSUE THREAD

**Issue by phron3sis** [Bot-detector/bot-detector#26]
Please create accounts on Twitter, Facebook, Reddit, etc.

Or at least Twitter. Would like to @bot-detector-plugin (or whatever you choose) when I complain about bots to @jagexSupport 

If you have a social media presence it will improve this plugin's adoption among players.

You can use IFTTT to automate social media: https://duckduckgo.com/?t=ffab&q=automate+social+media+ifttt

**Comment by Ferrariic** [comment]
Thank you! I'll set us up with a twitter :) I'll close this issues page once that has been completed.

**Comment by Ferrariic** [comment]
I made https://twitter.com/OSRSBotDetector

This should be good for now. I'm going to go ahead and close this for the time being - thanks!
