### ISSUE TITLE
[feature] add option to highlight "report" and "detect" in right-click context menu

### ISSUE THREAD

**Issue by phron3sis** [Bot-detector/bot-detector#30]
When i'm reporting bots that are stacked on top of each other my eyes are strained to find the report option:
https://i.imgur.com/ygjN5EP.png

Similar to how runelite highlights valuable items in the menu i'd like to see "report" highlighted :)

**Comment by Ferrariic** [comment]
I can see this being a toggled feature. Adding an enhancement tag. Good idea.

**Comment by Cyborger1** [comment]
Added with #79 and #90
