### ISSUE TITLE
See hiscores in plugin

### ISSUE THREAD

**Issue by extreme4all** [Bot-detector/bot-detector#43]
as a user i would like to see the stats of a player when reporting them.
Possible options:

1. redirect to hiscores plugin
2. redirect to hiscores page

Dev note:
hiscores page: [https://secure.runescape.com/m=hiscore_oldschool/hiscorepersonal?user1=extreme4all&submit=Search](https://secure.runescape.com/m=hiscore_oldschool/hiscorepersonal?user1=extreme4all&submit=Search)

**Comment by Cyborger1** [comment]
We are currently not interested in implementing cross-functionality with the hiscore plugin. You can copy paste the name from the prediction panel into the hiscore panel if you want to see their stats.

**Comment by Cyborger1** [comment]
Sorry extreme, but I've talked with Ferrariic and it's not something that would be possible for us to implement.
