### ISSUE TITLE
WebLink value somehow being overwritten

### ISSUE THREAD

**Issue by lgs-solo** [Bot-detector/bot-detector#44]
When clicking on the "GitHub" icon within the UIPanel of the plugin, Runelite opens "https://github.com/Belieal/flipping-utilities" (the GitHub link for another plugin that I have). 

It appears as if the WebLink value in BotDetectorPanel.java#49  is - for some weird reason - being overwritten by that of another plugin. At first I thought it was just an incorrect link put into the code, but after cloning and looking into the source-code I quickly found out that was not the issue.

Edit: I can, of course, provide any information necessary to help fix the issue (screen recordings, logs, etc.)

**Comment by Ferrariic** [comment]
Thank you :) this has been addressed in our latest refactor and should be resolved in our next release. Thanke!

**Comment by extreme4all** [comment]
@Ferrariic  you should add the relevant pull / issue
